### ISSUE TITLE
Georeferencing Error: Records found outside named county < .5 mile

### ISSUE THREAD

**Issue by dbloom** [flmnh-vertnet/ichthyology#27]
Hello UF,

The Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 12 records in the VertNet data portal that should plot within the bounds of the named county in the state of Kentucky, but actually plot outside the named county by half a mile or less.

If you'd like to discuss these issues with the folks at KFWIS, contact me and I will connect you with them.

Records below are Tab-Separated so you should be able to cut/paste into a spreadsheet so you can read them more easily.

institutioncode	collectioncode	catalognumber	county	decimallatitude	decimallongitude	geodeticdatum	coordinateuncertaintyinmeters
UF	Fish	174214	Graves	36.5025	-88.48416666	 	
UF	Fish	174215	Graves	36.5025	-88.48416666	 	
UF	Fish	174216	Graves	36.5025	-88.48416666	 	
UF	Fish	174220	Graves	36.5025	-88.48416666	 	
UF	Fish	174221	Graves	36.5025	-88.48416666	 	
UF	Fish	174222	Graves	36.5025	-88.48416666	 	
UF	Fish	174223	Graves	36.5025	-88.48416666	 	
UF	Fish	174224	Graves	36.5025	-88.48416666	 	
UF	Fish	174217	Graves	36.5025	-88.48416666	 	
UF	Fish	174218	Graves	36.5025	-88.48416666	 	
UF	Fish	174219	Graves	36.5025	-88.48416666	 	
UF	Fish	175725	Jackson	37.3342	-84.13609983	 	

(There may not be data contained within each Darwin Core field for each of these records.)

**Comment by rhrobins** [comment]
Corrections made. Thank you.

Best,

Rob

Robert H. Robins
Collection Manager
Division of Ichthyology
[FLMNH Fishes logo email small]
Florida Museum of Natural History
1659 Museum Road
Gainesville, FL 32611-7800
Office: (352) 273-1957
Fax: (352) 846-0287
rhrobins@flmnh.ufl.edu<mailto:rhrobins@flmnh.ufl.edu>
www.flmnh.ufl.edu<http://www.flmnh.ufl.edu/>

**Comment by tucotuco** [comment]
Hey Rob,

It is a good idea to close the issues in GitHub once they have been addressed so they don't linger in an apparent state of "to-do". To do so, you can click on the link "View it in GitHub" in the email and on the resulting page click on the button "Close issue". Alternatively, you can make a comment there in GitHub and then close it. I'll leave this one open as a test to see if you can get it to work easily enough.

Cheers,

John

**Comment by rhrobins** [comment]
John,
I confess that I have no recollection of my username or password (like all of us, I am exceedingly weary of user names and passwords; if a site requires one, I don’t patronize it) and while I greatly relish the opportunity to improve our data, I’m way too tapped to do more than correct the information at the source – our database -- and move on.

With apologies,

Rob

Robert H. Robins
Collection Manager
Division of Ichthyology
[FLMNH Fishes logo email small]
Florida Museum of Natural History
1659 Museum Road
Gainesville, FL 32611-7800
Office: (352) 273-1957
Fax: (352) 846-0287
rhrobins@flmnh.ufl.edu<mailto:rhrobins@flmnh.ufl.edu>
www.flmnh.ufl.edu<http://www.flmnh.ufl.edu/>

**Comment by tucotuco** [comment]
No worries. In that case, when you fix the issues and respond, could you add something like "Please close the issue" so that we know to do it for you?

Closing this one now.

**Comment by dbloom** [comment]
Thanks Rob!

**Comment by rhrobins** [comment]
Much obliged!

Rob

Robert H. Robins
Collection Manager
Division of Ichthyology
[FLMNH Fishes logo email small]
Florida Museum of Natural History
1659 Museum Road
Gainesville, FL 32611-7800
Office: (352) 273-1957
Fax: (352) 846-0287
rhrobins@flmnh.ufl.edu<mailto:rhrobins@flmnh.ufl.edu>
www.flmnh.ufl.edu<http://www.flmnh.ufl.edu/>
